POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "admin33",
    "email": "admin33@admin.com",
    "password": "admin",
    "phone_number": 843535930,
    "full_name": "ẹt min backup"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

