POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "admin2",
    "email": "admin2@admin.com",
    "password": "Admin2@",
    "phone_number": "0356606060",
    "full_name": "sửu nè!!!"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:8080/api/user/6229a6959208004560281bb3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5YTY5NTkyMDgwMDQ1NjAyODFiYjMiLCJpYXQiOjE2NDY5MDAwNjl9._oPbL5MvD3M7citDiH7-4OH1hxzH9Q14qroLulGFmgg

###
GET http://localhost:8080/api/user
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5YTY5NTkyMDgwMDQ1NjAyODFiYjMiLCJpYXQiOjE2NDY5MDAwNjl9._oPbL5MvD3M7citDiH7-4OH1hxzH9Q14qroLulGFmgg

###
DELETE http://localhost:8080/api/user/622868fe70d90916b8124cd9


### LEAGUE API TESTING
GET http://localhost:8080/api/league/

###
POST http://localhost:8080/api/league/
Content-Type: application/json; charset=utf-8

{
    "lg_name": "AFF22",
    "lg_teams": ["team01", "team02", "team03"]
}

###
POST http://localhost:8080/api/league/622ad8e8b275ba361ce1c05c/addteam
Content-Type: application/json

{
    "teamId": "team04"
}